= Overview of Maven modularity

In order to reduce code duplication, make maintenance easier and allow
better customisation control, the Stacks Workloads use the following
internal dependencies:

== Common Modules

These modules are shared modules, independant of the cloud provider
selected: -

TODO internal links
* link:/docs/workloads/common/backend/java/architecture/dependency_parent_java[Stacks
modules parent], found in
https://github.com/amido/stacks-java-module-parent[stacks-java-module-parent]
* link:/docs/workloads/common/backend/java/architecture/dependency_commons_java[Stacks
commons core module], found in
https://github.com/amido/stacks-java-core-commons[stacks-java-core-commons]
* link:/docs/workloads/common/backend/java/architecture/dependency_api_java[Stacks
commons API module], found in
https://github.com/amido/stacks-java-core-api[stacks-java-core-api]
* link:/docs/workloads/common/backend/java/architecture/dependency_cqrs_java[Stacks
commons CQRS module], found in
https://github.com/amido/stacks-java-core-cqrs[stacks-java-core-cqrs]
* link:/docs/workloads/common/backend/java/architecture/dependency_messaging_java[Stacks
messaging core module], found in
https://github.com/amido/stacks-java-core-messaging[stacks-java-core-messaging]

== Azure Capability Modules

Capabilities are provided by the Azure cloud platform: -

* link:/docs/workloads/azure/backend/java/architecture/dependency_servicebus_java[Stacks
Azure Service Bus module], found in
https://github.com/amido/stacks-java-azure-servicebus[stacks-java-azure-servicebus]
* link:/docs/workloads/azure/backend/java/architecture/dependency_cosmos_java[Stacks
Azure CosmosDB module], found in
https://github.com/amido/stacks-java-azure-cosmos[stacks-java-azure-cosmos]

== AWS Capability Modules

Capabilities are provided by the AWS cloud platform: -

* link:/docs/workloads/aws/backend/java/architecture/dependency_sqs_java[Stacks
AWS SQS module], found in
https://github.com/amido/stacks-java-aws-sqs[stacks-java-aws-sqs]
* link:/docs/workloads/aws/backend/java/architecture/dependency_dynamodb_java[Stacks
AWS DynamoDB module], found in
https://github.com/amido/stacks-java-aws-dynamodb[stacks-java-aws-dynamodb]

The modules are built and published independently of the Workloads and
by default are pulled into the project as Maven dependencies. You can
easily replace these by cloning individual repositories and placing them
in your application either directly or as modules.