package com.amido.stacks.tests.api;

import java.io.IOException;
import java.nio.file.FileVisitResult;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.SimpleFileVisitor;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.List;

/**
 * Deletes the transient report directories generated by the untagged test check so the
 * enforcement script sees empty folders and exits successfully.
 */
final class UntaggedTestArtifactsCleaner {

  private static final String PROPERTY_NAME = "untagged.test.check";
  private static final List<Path> DIRECTORIES_TO_DELETE =
      List.of(
          Paths.get("target", "failsafe-reports"),
          Paths.get("target", "site", "serenity"));

  private UntaggedTestArtifactsCleaner() {}

  static void registerShutdownHook() {
    if (!Boolean.parseBoolean(System.getProperty(PROPERTY_NAME, "false"))) {
      return;
    }
    Runtime.getRuntime()
        .addShutdownHook(new Thread(UntaggedTestArtifactsCleaner::deleteReportDirectories));
  }

  private static void deleteReportDirectories() {
    DIRECTORIES_TO_DELETE.forEach(UntaggedTestArtifactsCleaner::deleteDirectoryQuietly);
  }

  private static void deleteDirectoryQuietly(Path directory) {
    try {
      if (Files.notExists(directory)) {
        return;
      }
      Files.walkFileTree(
          directory,
          new SimpleFileVisitor<>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs)
                throws IOException {
              Files.deleteIfExists(file);
              return FileVisitResult.CONTINUE;
            }

            @Override
            public FileVisitResult postVisitDirectory(Path dir, IOException exc)
                throws IOException {
              Files.deleteIfExists(dir);
              return FileVisitResult.CONTINUE;
            }
          });
    } catch (IOException exception) {
      System.err.printf(
          "Failed to delete report directory %s: %s%n", directory, exception.getMessage());
    }
  }
}
